services:
  - type: web
    name: mailblaster
    env: php
    plan: free
    rootDir: MailBlaster
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://<TU_URL_RENDER>.onrender.com
      - key: APP_NAME
        value: MailBlaster
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: bdz9pi5f1rtd05ghwghv-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: "20597"
      - key: DB_DATABASE
        value: bdz9pi5f1rtd05ghwghv
      - key: DB_USERNAME
        value: urcvef2jzkrvxwjy
      - key: DB_PASSWORD
        value: WspHBJnjH0UKC3NwUeC
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mail.deur.com.co
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        value: test@deur.com.co
      - key: MAIL_PASSWORD
        value: UWy!M2Q2rau*
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: test@deur.com.co
      - key: MAIL_FROM_NAME
        value: MailBlaster
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: CACHE_STORE
        value: database
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: VITE_APP_NAME
        value: MailBlaster